replicaCount: 1

image:
  repository: 046573050373.dkr.ecr.eu-central-1.amazonaws.com/okuto-production
  pullPolicy: Always
  tag: "latest"

labels:
  env: "staging"

service:
  port: 80
  targetPort: 80
  type: LoadBalancer


autoscaling:
  enabled: false

ingress:
  enabled: false

imagePullSecrets:
  - name: regcred
