replicaCount: 1

image:
  repository: $AWS_ECR_ACCOUNT_URL/$AWS_ECR_REPO_NAME
  pullPolicy: Always
  tag: "latest"

labels:
  env: "staging"

service:
  port: 80
  targetPort: 80
  type: LoadBalancer


autoscaling:
  enabled: false

ingress:
  enabled: false

imagePullSecrets:
  - name: regcred
